### PR TITLE
Fix deprecated File.exists? call which got removed in Ruby 3.2

### PR DESCRIPTION
**Pull request by djfpaagman**
The install task does not work on Ruby 3.2 right now:

```
❯ bundle exec database_consistency install
bundler: failed to load command: database_consistency (/Users/dennis/.asdf/installs/ruby/3.2.0/bin/database_consistency)
/Users/dennis/.asdf/installs/ruby/3.2.0/lib/ruby/gems/3.2.0/gems/database_consistency-1.7.3/bin/database_consistency:10:in `<top (required)>': undefined method `exists?' for File:Class (NoMethodError)

  file_exists = File.exists?(default_config)
                    ^^^^^^^^
Did you mean?  exist?
```

`File.exists?` already [got deprecated in 2.1.0](https://bugs.ruby-lang.org/issues/17391) but [they only removed it in 3.2.0](https://github.com/ruby/ruby/commit/bf97415c02b11a8949f715431aca9eeb6311add2).

### CODE REVIEW

**Comment by djezzzl** [comment]
Hi @djfpaagman ,

Thank you again for the fix! I've released it in 1.7.4. Please try it out and let me know if it doesn't work. I'm sorry that it took me long to release. 

Have a great weekend!
